// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(WebChatContext))]
    [Migration("20220524135436_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApi.Models.Contact", b =>
                {
                    b.Property<string>("UsernameOfContact")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactOfUser")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NicknameOfContact")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lastMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("server")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsernameOfContact", "ContactOfUser");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("WebApi.Models.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("from")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Property<string>("UsernameOfUser")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsernameOfUser");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
